language: node_js

node_js:
  - '4'
  - '6'
  - '8'
  - '10'

before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi

cache:
  directories:
    - node_modules

after_success:
  - npm run cover:alls

sudo: false
